export const ROUTES = {
  home: '/',
  pricing: '/pricing',
  about: '/about',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  verifyEmailOtp: '/verify-email-otp',
  selectPlan: '/select-plan',
  dashboard: '/dashboard',
  settings: '/settings',
  leads: '/leads',
  leadUpload: '/leads/upload',
  lead: (id: string) => `/leads/${id}` as const,
  templates: '/templates',
  templateNew: '/templates/new',
  template: (id: string) => `/templates/${id}` as const,
  campaigns: '/campaigns',
  campaign: (id: string) => `/campaigns/${id}` as const,
  conversations: '/conversations',
  conversation: (id: string) => `/conversations/${id}` as const,
  admin: {
    root: '/admin',
    users: '/admin/users',
    user: (id: string) => `/admin/users/${id}` as const,
    leadRequests: '/admin/lead-requests',
    campaigns: '/admin/campaigns',
  },
  finance: {
    login: '/finance/login',
    dashboard: '/finance/dashboard',
    transactions: '/finance/transactions',
    insights: '/finance/insights',
  },
} as const;
